### ISSUE TITLE
Accept transform options provided upstream

### ISSUE THREAD

**Issue by milotoor** [benbria/browserify-transform-tools#7]
Browserify's API for writing transforms allows transforms to accept two parameters: the `file` name, which is mandatory if the transform is to do anything meaningful; and `trOpts`, or transform options, which are optional but can be used by the transform if it so chooses.

Presently, the `make*Transform` methods all return a function that accepts a `file` parameter but no `trOpts`. Consequently it's impossible for any parameters provided to the transform from somewhere upstream (i.e. via Browserify's own `b.transform` API, or a build tool such as grunt-browserify) to be processed by the created transform.

I propose modifying the function signature of the `transform` function returned by `makeStringTransform` (see [`transformTools.coffee` line 53](https://github.com/benbria/browserify-transform-tools/blob/master/src/transformTools.coffee#L53)) from

```coffeescript
transform = (file) ->
```

to

```coffeescript
transform = (file, opts) ->
```

and to change the `transformOptions` from

```coffeescript
transformOptions = {
    file: file,
    configData, configData,
    config: configData?.config
}
```

to

```coffeescript
transformOptions = {
    file: file,
    configData, configData,
    config: configData?.config,
    opts: opts
}
```

Thoughts?

**Comment by jwalton** [comment]
Yeah, when I wrote browserify-transform-tools, browserify didn't allow that second parameter, and there was much debate about whether it should or not over in the browserify repo.  Now that they support it, we probably should, too; I think this is a much better way to pass options.

**Comment by milotoor** [comment]
Alright, I'm happy to put together a pull request.

**Comment by jwalton** [comment]
That would be awesome.  :)

**Comment by milotoor** [comment]
See #8. Criticism wholeheartedly welcome!

**Comment by jwalton** [comment]
Published to npm.  Enjoy!  :)

**Comment by milotoor** [comment]
Thank you!
